Feature/profiel
SE-2-Groep-D/Panel pull request #40
Opened 2024-01-14 17:59 UTC by JJK67

Je kan nu je profiel informatie bekijken en updaten.
Je kan nog niet alles zien/updaten omdat de endpoint nog geupdate moet worden.
Het veranderen van de email werkt wel maar doet nog een beetje gek.

2024-01-15 09:07 UTC, Ozancann01 reviewed
Als ik de omschrijving langer maak, dan breekt de CSS. Je moet dit dan even aanpassen.

2024-01-18 11:20 UTC, DavidOut03 requested changes

2024-01-18 11:20 UTC, DavidOut03 commented on src/styles/page/account/_loginRegister.scss
Ik zou deze styles nog binnen de haakjes van je login/register form doen omdat het anders ook overslaat op andere styles van andere paginas.

2024-01-18 15:33 UTC, DavidOut03 approved these changes

2024-01-18 15:33 UTC, merged