Feature/onderzoek
SE-2-Groep-D/Panel pull request #8
Opened 2023-12-28 20:14 UTC by Ozancann01

2023-12-29 13:18 UTC, DavidOut03 requested changes
Ik heb een aantal punten toegevoegd. Kijk goed naar de componenten die ik heb gemaakt waarschijnlijk zit er dingen bij die je handig kan gebruiken.

2023-12-29 13:18 UTC, DavidOut03 commented on src/Routing.jsx
> +import AlgemeneOnderzoek from "@pages/research/AlgemeneOnderzoek.jsx";
Ik zou de namen van de bestanden veranderen naar Onderzoeken en OnderzoekInfo. Dit is iets specifieker.

2023-12-29 13:18 UTC, DavidOut03 commented on src/Routing.jsx
> +                <Route path="/onderzoeklist" element={<AlgemeneOnderzoek />}> </Route>
Ik zou de path veranderen naar /onderzoek en /onderzoek/onderzoekId dit is wat meer consistent en dan word het voor iedereen net wan duidelijker.

2023-12-29 13:18 UTC, DavidOut03 commented on src/pages/index.jsx
> +export {default as Research} from './research/Onderzoek.jsx'
Zorg er weer voor dat je hier aan lazy loading doet.

2023-12-29 13:18 UTC, DavidOut03 commented on src/pages/research/context/OnderzoekContext.js
> +const baseUrl = 'http://localhost:3001/Onderzoek'; // Dit is tijdelijk
Deze hoeft er never nooit in als je iets van de API wil. Je kan dan gewoon /api/onderzoek doen. Dit heb ik gedaan doormiddel van een proxy. Je kan ook deze methode gebruiken.


Dit staat in api.js
```
async function fetchData(endpoint) {
    try {
        const response = await fetch('/api' + endpoint);
        if(!response.ok) {
            throw new Error(`HTTP error! Status: ${response.status}`);
        }
        
        return await response.json();
    } catch (error) {
        console.log('Error while fetching data: ', error);
        throw error;
    }
}

export {fetchData};

```

2023-12-29 13:18 UTC, DavidOut03 commented on src/pages/research/AlgemeneOnderzoek.jsx
> +    if (isLoading) return <div>Loading...</div>;
Ik heb speciaal een loading div component hiervoor gemaakt.

Je kan hem gebruiken als component en wanneer loading op true staat komt er een loading animatie.

dus dan gebruik je

```
<LoadingDiv loading={loading}>
    // jou logica
</LoadingDiv>
```



```

export default function LoadingDiv({children, loading}) {    
    const className = (loading) ? 'loading-div loading' : 'loading-div ';
  return (
    <div className={className}>
        {children}
    </div>
  )
}

```

2023-12-29 13:18 UTC, DavidOut03 commented on src/pages/research/Onderzoek.jsx
> +    }
Hier geld het zelfde gebruik de loading div

2023-12-29 13:18 UTC, DavidOut03 commented on src/pages/research/components/map.jsx
> +
Gebruikt deze al het adres van het onderzoek/bedrijf?

2023-12-29 13:18 UTC, DavidOut03 commented on src/styles/page/algemeneOnderzoek.scss
> +  width: 80%; /* Stel de breedte in op 80% van de #root */
Ik zou eerder gewoon de breedte zetten met rems en dan evetueel verkleinen met deze code.

```
 @include respond(mobile) {
        width: 35rem;
  }

```

2023-12-29 13:18 UTC, DavidOut03 commented on src/pages/research/AlgemeneOnderzoek.jsx
> +    if (error) return <div>Error: {error}</div>;
Zorg ervoor dat hier een goede error message staat. Gebruikers zullen niks snappen. Dus bijvoorbeeld 'Kon onderzoek helaas niet vinden.' Ik zal hiervoor nog wel een design maken als dit nodig is. 

Zorg er ook voor dat het een juiste font-size heeft.

2023-12-29 13:18 UTC, DavidOut03 commented on src/styles/page/research.scss
> +    width: 45%;
.

2023-12-29 13:23 UTC, DavidOut03 commented on src/pages/research/context/OnderzoekContext.js
> +
Kan je deze file vernoemen naar onderzoekservice.jsx dat is iets duidelijker want een context staat eigenlijk voor iets anders.

2023-12-29 15:53 UTC, DavidOut03 commented on src/pages/research/AlgemeneOnderzoek.jsx
> +                <div className="onderzoek-tabel">
Ik zou hier de main component gebruiken zodat de screen recorders weten wat ze als eerst mee moeten pakken.

2023-12-29 17:43 UTC, Ozancann01 commented on src/pages/research/components/map.jsx
> +
nee nog niet.

2023-12-29 18:31 UTC, Ozancann01 commented on src/pages/research/AlgemeneOnderzoek.jsx
> +                <div className="onderzoek-tabel">
ik snap je hier niet wat bedoel je precies

2023-12-30 00:07 UTC, DavidOut03 commented on src/pages/research/AlgemeneOnderzoek.jsx
> +                <div className="onderzoek-tabel">
<main> </main>

2023-12-30 00:08 UTC, DavidOut03 commented on src/pages/research/AlgemeneOnderzoek.jsx
> +                <div className="onderzoek-tabel">
Maak hier <main className=“onderzoeken”> </main>

2023-12-30 00:10 UTC, DavidOut03 commented on src/pages/research/AlgemeneOnderzoek.jsx
> +                <div className="onderzoek-tabel">
Gebruik de ‘’’ < main > </main ‘’

2024-01-03 13:15 UTC, Ozancann01 reviewed
feedback van David is verwerkt.

2024-01-03 13:36 UTC, DavidOut03 requested changes

2024-01-03 13:36 UTC, DavidOut03 commented on panel/src/App.jsx
> +            <Suspense fallback={<div>Loading...</div>}>
Kan je dit een Loading div maken

2024-01-03 13:36 UTC, DavidOut03 commented on panel/src/App.jsx
> +const AlgemeneOnderzoek = React.lazy(() => import('@pages/research/AlgemeneOnderzoek.jsx'));
Kan je dit bestand vernoemen Naar Onderzoeken.jsx

2024-01-03 13:36 UTC, DavidOut03 commented on panel/src/App.jsx
> +const Onderzoek = React.lazy(() => import('@pages/research/Onderzoek.jsx'));
Kan je dit bestand vernoemen Naar OnderzoekInfo.jsx

2024-01-03 13:36 UTC, DavidOut03 commented on panel/src/Routing.jsx
> +import AlgemeneOnderzoek from "@pages/research/AlgemeneOnderzoek.jsx";
Dit bestand kan je verwijderen

2024-01-03 13:36 UTC, DavidOut03 commented on panel/src/pages/research/AlgemeneOnderzoek.jsx
> +
Kan je de fetch hierboven misschien nog in een aparte async functie toepassen. 
Op deze manier maak je de code wat minder groot.

```
async function fetchResearchData(id, setData) {
  if(id === undefined || id === null) return;
  try {
      const data = await fetchData(`/vragenlijst/${id}`);
      setData(data)
  } catch (err) {
      setData(err);
  }
}

```

2024-01-03 13:36 UTC, DavidOut03 commented on panel/src/pages/research/AlgemeneOnderzoek.jsx
> +        <LoadingDiv loading={isLoading}>
Je kan een loading property maken of je kan dit ook omzetten tot een if statement dan werkt dit ook.

Zo heb ik het gedaan.

```
export default function Results() {
    const [options, setOptions] = useState(undefined);
    const [selectedOption, setSelectedOption] = useState();

    useEffect(() => {
        fetchOptions(setOptions);
    }, []);


    const ResultsComponent = renderedResults(options, selectedOption);
    const inputOptions = getOptionsList(options);

  return (
    <main className='results'>
            <div className='navigation'>
                <a href='/' className='back'>
                    <Icon type="back" size="17"/>
                    Terug
                </a>

                <OptionSelector onChange={(e) => setSelectedOption(e.value)} options={inputOptions} value={selectedOption}>Resultaten</OptionSelector>
            </div>

            <LoadingDiv loading={options === undefined}>
                    {ResultsComponent}
            </LoadingDiv>
        </main>
    );
}
```

2024-01-03 13:36 UTC, DavidOut03 commented on panel/src/pages/research/Onderzoek.jsx
> +    };
Je kan deze functie nog async maken zo kan je deze wat korter maken.

2024-01-03 13:36 UTC, DavidOut03 commented on panel/src/pages/research/Onderzoek.jsx
> +    }, [onderzoekId]); // onderzoekId is de enige dependency hier
Zelfde geld voor deze kijk of je de fetch korter en duidelijker kan maken door een async functie

2024-01-03 13:36 UTC, DavidOut03 commented on panel/src/pages/research/components/OnderzoekInformatie.jsx
> +    console.log(bedrijf); // Dit zal 'null' loggen totdat het is ingesteld
Kan je deze log verwijderen

2024-01-03 13:36 UTC, DavidOut03 commented on panel/src/pages/research/context/bedrijfservice.js
> +export const fetchBedrijfById = (id) => {
Kan je deze vernoemen naar fetchUserData

2024-01-03 13:36 UTC, DavidOut03 commented on panel/src/styles/page/algemeneOnderzoek.scss
> +  width: 80%;
Kan je breedte 80% omzetten naar clamp en gebruik REM

```
width: clamp(min_width, default_width, max_width);
```

2024-01-03 13:36 UTC, DavidOut03 commented on panel/src/styles/page/algemeneOnderzoek.scss
> +  @media (max-width: 900px) {
Kan je de mixin gebruiken die hier voor is gemaakt. Als die nog niet in development staat zet je deze in mixinx

```
$breakpoints: (
  mobile: 200px,
  tablet: 768px,
  laptop: 1024px,
  desktop: 1200px
);

@mixin respond($breakpoint, $type: max) {
  @if map-has-key($breakpoints, $breakpoint) {
    $value: map-get($breakpoints, $breakpoint);
    @if $type == min {
      @media (min-width: #{$value}) {
        @content;
      }
    } @else if $type == max {
      @media (max-width: #{$value}) {
        @content;
      }
    } @else {
      @error "Invalid type: #{$type}. Please use 'min' or 'max'.";
    }
  } @else {
    @if $type == min {
      @media (min-width: #{$breakpoint}) {
        @content;
      }
    } @else if $type == max {
      @media (max-width: #{$breakpoint}) {
        @content;
      }
    } @else {
      @error "Invalid type: #{$type}. Please use 'min' or 'max'.";
    }
  }
}

```

2024-01-03 13:36 UTC, DavidOut03 commented on panel/src/styles/page/algemeneOnderzoek.scss
> +  }
Zou je hier ook de mixin willen gebruiken uit mixins.

```
 @include respond(tablet) {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        
         @include respond(phone, min) {
            color: red
        }

 @include respond(600px, min) {
            color: blue
        }
```

2024-01-03 14:14 UTC, Ozancann01 commented on panel/src/pages/research/AlgemeneOnderzoek.jsx
> +
bedoel je het zo? 
`
    useEffect(() => {
        async function fetchAllOnderzoeken() {
            try {
                const data = await fetchData('/Onderzoek/list');
                setOnderzoeken(data);
                setIsLoading(false)
            } catch (err) {
                setError(err);
            }
        }

        fetchAllOnderzoeken();
    }, []);
`

2024-01-03 14:17 UTC, DavidOut03 commented on panel/src/pages/research/AlgemeneOnderzoek.jsx
> +
jes sir

2024-01-03 14:35 UTC, Ozancann01 commented on panel/src/pages/research/context/bedrijfservice.js
> +export const fetchBedrijfById = (id) => {
ik heb deze weg gehaalt.  We hebben niet meer nodig.Als we op jouw manier doen want dan roepen wij gelijk de fetchdata aan met de url bij 
![image](https://github.com/SE-2-Groep-D/Panel/assets/63856146/ffaedf6e-bec7-4a32-95c8-58ea83403436)

2024-01-03 15:22 UTC, Ozancann01 commented on panel/src/pages/research/AlgemeneOnderzoek.jsx
> +        <LoadingDiv loading={isLoading}>
hij werkt het al? het is toch een if statemen al!

2024-01-03 16:05 UTC, DavidOut03 requested changes

2024-01-03 16:05 UTC, DavidOut03 commented on panel/src/pages/setup-account/form/research-info.jsx
> +            <Form title="OnderzoekInfo Informatie" buttonText='volgende' message={message} onSubmit={handleSubmit} move={move}>
Deze kan ook Onderzoek blijven

2024-01-03 16:16 UTC, DavidOut03 approved these changes

2024-01-03 16:17 UTC, merged